@startuml
title SmartHome HeatingService Code Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

class HeatingScenarioService {
    +HeatingScenarioDto saveScenario(HeatingScenarioDto scenario)
    +HeatingScenarioDto getScenario(Long id)
    +HeatingScenarioDto updateScenario(Long id, HeatingScenarioDto scenario)
    +HeatingScenarioDto enableScenario(Long id)
    +HeatingScenarioDto disableScenario(Long id)
    +void scheduledAllScenaries() //запуск всех задач по их расписанию
}

class HeatingConditionService {
  +HeatingCondition saveCondition(HeatingCondition condition)
  +List<HeatingCondition> findConditions(SearchFilterDto filter)
}

class SearchFilterDto {
  +Long startDate
  +Long endDate
  +List<Long> houseIds
}

class HeatingScenario {
  +Long id
  +Long userId
  +Long heatingId
  +String cron
  +boolean active
  +boolean isSystem
}

class Heating {
  +Long id
  +Long userId
  +boolean isOn
  +Double targetTemperature
  +Double currentTemperature
}

class HeatingCondition {
  +Long id
  +Long houseId
  +Double currentTemperature
  +Date createdDate
}

HeatingScenarioService -- HeatingScenario : use
HeatingScenarioService -- HeatingConditionService : use
HeatingConditionService -- HeatingCondition : use
HeatingConditionService -- SearchFilterDto : use
HeatingScenario "1" -- "0..*" Heating : has


@enduml